package FillForm;

import javax.swing.JOptionPane;

import Employment.MainMenu;

/**
 *
 * @author STASPNUT
 */
public class FillFormApplicant extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
	
    private javax.swing.JTextField ap_address;
    private javax.swing.JTextField ap_chw;
    private javax.swing.JTextField ap_ed;
    private javax.swing.JTextField ap_id;
    private javax.swing.JTextField ap_maj;
    private javax.swing.JTextField ap_name;
    
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JComboBox cb4;
    private javax.swing.JComboBox cb5;
    
    
    private javax.swing.JButton ok;
    private javax.swing.JButton edit;
    
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23; 
    
    
    
    private javax.swing.JComboBox pb1;
    private javax.swing.JComboBox pb2;
    private javax.swing.JComboBox pb3;
    
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t14;
    private javax.swing.JLabel t15;
   
    // End of variables declaration//GEN-END:variables
    
    /**
     * Creates new form Form1
     */
    String ap_sex = "";
    MainMenu mainMenu;
    public FillFormApplicant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        
        ok 		= new javax.swing.JButton();
        edit 	= new javax.swing.JButton();
        
        jLabel1 = 	new javax.swing.JLabel();
        jLabel2 = 	new javax.swing.JLabel();
        jLabel3 = 	new javax.swing.JLabel();
        jLabel4 = 	new javax.swing.JLabel();
        jLabel5 = 	new javax.swing.JLabel();
        jLabel6 = 	new javax.swing.JLabel();
        jLabel7 = 	new javax.swing.JLabel();
        jLabel8 = 	new javax.swing.JLabel();
        jLabel9 = 	new javax.swing.JLabel();
        jLabel10 = 	new javax.swing.JLabel();
        jLabel11 = 	new javax.swing.JLabel();
        jLabel12 = 	new javax.swing.JLabel();
        jLabel13 = 	new javax.swing.JLabel();
        jLabel14 = 	new javax.swing.JLabel();
        jLabel15 = 	new javax.swing.JLabel();
        jLabel16 = 	new javax.swing.JLabel();
        jLabel17 = 	new javax.swing.JLabel();
        jLabel18 = 	new javax.swing.JLabel();
        jLabel19 = 	new javax.swing.JLabel();
        jLabel20 = 	new javax.swing.JLabel();
        jLabel21 = 	new javax.swing.JLabel();
        jLabel22 = 	new javax.swing.JLabel();
        jLabel23 = 	new javax.swing.JLabel();
        
        ap_name 	= 	new javax.swing.JTextField();
        ap_address 	= 	new javax.swing.JTextField();
        ap_id 		= 	new javax.swing.JTextField();             
        ap_ed 		= 	new javax.swing.JTextField();
        ap_maj 		= 	new javax.swing.JTextField();
        ap_chw 		= 	new javax.swing.JTextField();
        
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        cb3 = new javax.swing.JComboBox();
        cb4 = new javax.swing.JComboBox();
        cb5 = new javax.swing.JComboBox();
        pb1 = new javax.swing.JComboBox();
        pb2 = new javax.swing.JComboBox();
        pb3 = new javax.swing.JComboBox();
       
        t1 = 	new javax.swing.JLabel();
        t2 = 	new javax.swing.JLabel();
        t3 = 	new javax.swing.JLabel();
        t4 = 	new javax.swing.JLabel();
        t5 = 	new javax.swing.JLabel();
        t6 = 	new javax.swing.JLabel();
        t7 = 	new javax.swing.JLabel();
        t8 = 	new javax.swing.JLabel();
        t9 = 	new javax.swing.JLabel();
        t10 = 	new javax.swing.JLabel();
        t11 = 	new javax.swing.JLabel();
        t12 = 	new javax.swing.JLabel();
        t13 = 	new javax.swing.JLabel();
        t14 = 	new javax.swing.JLabel();
        t15 = 	new javax.swing.JLabel();

        //setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());



        p1.setMaximumSize(new java.awt.Dimension(2800, 2900));

        ok.setText("ตกลง");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("บริษัท STOU-TEC จำกัด ");

        jLabel2.setText("ชื่อ-นามสกุล  (AP_NAME) :");

        jLabel3.setText("ที่อยู่  (AP_ADDRESS)  :");

        jLabel4.setText("เลขประจำตัวของผู้สมัคร  (AP_ID)  :");

        jLabel5.setText("เพศ  (AP_SEX) :");

        ap_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_nameActionPerformed(evt);
            }
        });

        ap_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_addressActionPerformed(evt);
            }
        });

        ap_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_idActionPerformed(evt);
            }
        });

     

        r1.setSelected(true);
        r1.setText("ชาย");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setText("หญิง");
        
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ใบสมัครสำหรับงานด้าน ICT นี้   ให้ผู้สมัครกรอกรายละเอียดต่อไปนี้เพื่อที่");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("แบบฟอร์มใบสมัครพนักงาน");

        

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("บริษัท STOU-TEC จำกัด ทำการคัดเลือกตามความเหมาะสม");

        jLabel11.setText("วุฒิการศึกษาชั้นสูงสุด  (AP_ED) :");

        jLabel12.setText("วิชาเอก  (AP_MAJ) :  ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ความรู้ความสามารถหรือคุณสมบัติเฉพาะตำแหน่ง  (QUAL_DESC) (ตอบได้ไม่เกิน 5 รายการ )");

        jLabel15.setText("ความรู้ความสามารถ 1");

        jLabel16.setText("ความรู้ความสามารถ 2");

        jLabel17.setText("ความรู้ความสามารถ 3");

        jLabel18.setText("ความรู้ความสามารถ 4");

        jLabel19.setText("ความรู้ความสามารถ 5");

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "เลือกความรู้ความสามารถ 1", "Web_ASP", "C++", "Database Administrator,DB2", "Database Administrator,ORACLE", "Graphic Design", "JAVA", "Management                    ", "Network ", "Secretarial work,45 words/min ", "Secretarial work,60 words/min", "System Analyst, Level 1        ", "System Analyst, Level 2        ", "Visual Basic", " " }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "เลือกความรู้ความสามารถ 2", "Web_ASP", "C++", "Database Administrator,DB2", "Database Administrator,ORACLE", "Graphic Design", "JAVA", "Management                    ", "Network ", "Secretarial work,45 words/min ", "Secretarial work,60 words/min", "System Analyst, Level 1        ", "System Analyst, Level 2        ", "Visual Basic" }));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "เลือกความรู้ความสามารถ 3", "Web_ASP", "C++", "Database Administrator,DB2", "Database Administrator,ORACLE", "Graphic Design", "JAVA", "Management                    ", "Network ", "Secretarial work,45 words/min ", "Secretarial work,60 words/min", "System Analyst, Level 1        ", "System Analyst, Level 2        ", "Visual Basic" }));

        cb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "เลือกความรู้ความสามารถ 4", "Web_ASP", "C++", "Database Administrator,DB2", "Database Administrator,ORACLE", "Graphic Design", "JAVA", "Management                    ", "Network ", "Secretarial work,45 words/min ", "Secretarial work,60 words/min", "System Analyst, Level 1        ", "System Analyst, Level 2        ", "Visual Basic" }));

        cb5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "เลือกความรู้ความสามารถ 5", "Web_ASP", "C++", "Database Administrator,DB2", "Database Administrator,ORACLE", "Graphic Design", "JAVA", "Management                    ", "Network ", "Secretarial work,45 words/min ", "Secretarial work,60 words/min", "System Analyst, Level 1        ", "System Analyst, Level 2        ", "Visual Basic" }));
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ตำแหน่งที่ต้องการสมัคร (POS_NAME)  :   (ตอบได้ไม่เกิน 3 ตำแหน่ง)   ");

        jLabel6.setText("ตำแหน่งที่ต้องการสมัคร 1");

        jLabel20.setText("ตำแหน่งที่ต้องการสมัคร 2");

        jLabel21.setText("ตำแหน่งที่ต้องการสมัคร 3");

        pb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "เลือกตำแหน่งที่ต้องการสมัคร 1 ", "Technical Programmer", "Web Developer             ", "General Manager          ", "ICT Specialist            ", "E-Business Analyst        ", "ICT Documentor            ", "Database Administrator    ", "PC Administrator          ", "Network Specialist        ", "ICT Manager", " " }));
        pb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb1ActionPerformed(evt);
            }
        });

        pb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "เลือกตำแหน่งที่ต้องการสมัคร 2", "Technical Programmer", "Web Developer             ", "General Manager          ", "ICT Specialist            ", "E-Business Analyst        ", "ICT Documentor            ", "Database Administrator    ", "PC Administrator          ", "Network Specialist        ", "ICT Manager", " " }));

        pb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "เลือกตำแหน่งที่ต้องการสมัคร 3", "Technical Programmer", "Web Developer             ", "General Manager          ", "ICT Specialist            ", "E-Business Analyst        ", "ICT Documentor            ", "Database Administrator    ", "PC Administrator          ", "Network Specialist        ", "ICT Manager", " " }));

        jLabel22.setText("(เช่น  B.S., B.A., M.S., M.BA., M.A.)");

        jLabel23.setText("จังหวัด  (AP_CHW) :");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(ok))
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ap_maj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                    .addComponent(ap_ed)
                                    .addComponent(ap_address, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ap_name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p1Layout.createSequentialGroup()
                                        .addComponent(r1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(r2))
                                    .addComponent(ap_id, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ap_chw, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                        .addGap(250, 250, 250))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(55, 55, 55)
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cb4, 0, 210, Short.MAX_VALUE)
                                    .addComponent(cb3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ap_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ap_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ap_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap_chw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(r1)
                    .addComponent(r2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ap_ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ap_maj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(pb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(p1, "card2");

        p2.setPreferredSize(new java.awt.Dimension(600, 600));

        edit.setText("แก้ไข");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        t1.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        
        t2.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        t2.setPreferredSize(new java.awt.Dimension(140, 14));

        t3.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        t3.setPreferredSize(new java.awt.Dimension(140, 14));

        t4.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        t4.setMaximumSize(new java.awt.Dimension(140, 14));

        t5.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        t6.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");    

        t7.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        t8.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        t9.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        t10.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        t11.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        t12.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        
        t13.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        t14.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        t15.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("รายละเอียดของผู้สมัคร");

       

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t14)
                    .addComponent(t13)
                    .addComponent(t6)
                    .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7)
                    .addComponent(t12)
                    .addComponent(t11)
                    .addComponent(t10)
                    .addComponent(t9)
                    .addComponent(t8)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t15))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(t1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t14)
                .addGap(19, 19, 19)
                .addComponent(edit)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        getContentPane().add(p2, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void ap_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap_addressActionPerformed

    private void ap_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap_nameActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
    	/* if(nametf.getText().isEmpty() || nametf.getText().length()< 5){
        warm("กรอกชื่อ 5 อักษร ขึ้นไป");
        return;
        }
        if(idtf.getText().isEmpty() || idtf.getText().length()== 13){
        warm("กรอกรหัสบัตรประชาชน 13 หลัก");
        return;
        }
        if(stdtf.getText().isEmpty() || stdtf.getText().length()== 10){
        warm("กรอกรหัสนักศึกษา 10 หลัก");
        return;
        }
        if(cb.getSelectedIndex()==0){
        warm("เลือกสาขาด้วย");
        return;
        }*/
    	if (r1.isSelected()) {
            ap_sex = "ชาย";
        } else {
            ap_sex = "หญิง";
        }

    	t1.setText("เลขประจำตัวของผู้สมัคร :" + ap_id.getText());
        t2.setText("ชื่อ-นามสกุล  :" + ap_name.getText());
        t3.setText("ที่อยู่  :" + ap_address.getText());        
        t4.setText("เพศ  :" + ap_sex);
        t5.setText("วุฒิการศึกษาชั้นสูงสุด :" + ap_ed.getText());
        t6.setText("วิชาเอก :" + ap_maj.getText());
        t7.setText("ความรู้ความสามารถ 1: " + cb1.getSelectedItem());
        t8.setText("ความรู้ความสามารถ 2: " + cb2.getSelectedItem());
        t9.setText("ความรู้ความสามารถ 3: " + cb3.getSelectedItem());
        t10.setText("ความรู้ความสามารถ 4: " + cb4.getSelectedItem());
        t11.setText("ความรู้ความสามารถ 5: " + cb5.getSelectedItem());
        t12.setText("ตำแหน่งที่ต้องการสมัคร 1: " + pb1.getSelectedItem());
        t13.setText("ตำแหน่งที่ต้องการสมัคร 2: " + pb2.getSelectedItem());
        t14.setText("ตำแหน่งที่ต้องการสมัคร 3: " + pb3.getSelectedItem());
        t15.setText("จังหวัด :" + ap_chw.getText());
        p1.setVisible(false);
        p2.setVisible(true);
    }//GEN-LAST:event_okActionPerformed

    private void ap_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap_idActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_editActionPerformed

    private void pb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FillFormApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FillFormApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FillFormApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FillFormApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FillFormApplicant().setVisible(true);
            }
        });
    }



    private void warm(String string) {
        JOptionPane.showMessageDialog(this, string, "แจ้งผิดพลาด", JOptionPane.WARNING_MESSAGE);
    }
}

